# Generated by Django 2.2.4 on 2019-08-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurnat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('orientation_requierd', models.IntegerField(choices=[(1, 'בשרים'), (2, 'סושיות'), (3, 'איטלקי'), (4, 'בר מסעדה'), (5, 'אסייתי'), (6, 'דגים'), (7, 'מזרחי'), (8, 'מקסיקני'), (9, 'גריל בר'), (10, 'ביתי'), (11, 'טבעוני'), (12, 'הודי'), (13, 'אמריקאי'), (14, 'צמחוני'), (14, 'ים תיכוני'), (14, 'תימני'), (14, 'דרום אמריקאי'), (14, 'טאפאס'), (14, 'אירופאי'), (14, 'אפריקאי'), (14, 'לטיני'), (14, "צ'רקסי")])),
                ('geolocation', models.IntegerField(choices=[(1, 'עפולה'), (2, 'חיפה'), (3, 'ירושליים'), (4, 'תל אביב'), (5, 'טבריה'), (6, 'רמת ישי'), (7, 'קריית שמונה')])),
                ('has_private_room', models.BooleanField()),
            ],
        ),
    ]
