# Generated by Django 2.2.4 on 2019-08-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurnat',
            name='has_private_room',
        ),
    ]
