# Generated by Django 2.2.4 on 2019-08-07 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20190807_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='short_description_text',
            field=models.CharField(max_length=150, verbose_name='describe the tag meaning'),
        ),
        migrations.CreateModel(
            name='TagMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurnat')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Tags')),
            ],
        ),
        migrations.AddField(
            model_name='tags',
            name='restaurants',
            field=models.ManyToManyField(through='restaurant.TagMatch', to='restaurant.Restaurnat'),
        ),
    ]
