# Generated by Django 2.2.4 on 2019-08-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('seconed_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('user_category', models.IntegerField(choices=[(1, 'new before payment'), (2, 'new first time payment'), (3, 'second time payment'), (4, 'returning client')])),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_business', models.CharField(max_length=100)),
                ('area', models.IntegerField(choices=[(1, 'Darom'), (2, 'Tzafon'), (3, 'Mercaz')])),
                ('cosher', models.BooleanField(default=False)),
                ('romantic', models.BooleanField(default=False)),
                ('has_private_room', models.BooleanField(default=False)),
                ('restaurant_category', models.IntegerField(choices=[(1, 'fast food'), (2, 'delux'), (3, 'other...')])),
            ],
        ),
    ]
