# Generated by Django 2.2.4 on 2019-08-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSourceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.CharField(max_length=200)),
                ('creation_date', models.DateField()),
                ('traffic_since_created', models.IntegerField(default=0)),
            ],
        ),
    ]
