# Generated by Django 2.2.4 on 2019-08-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSourceGroupingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_description', models.CharField(max_length=300)),
                ('extra_info', models.TextField(null=True)),
                ('match_type', models.IntegerField(choices=[(1, 'strong'), (2, 'May Be Interested...'), (3, 'suggetion_ilnks')])),
            ],
        ),
    ]
